version: '3.8'

services:
  blog-web:
    container_name: blog-web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: ghcr.io/coryball/blog/web:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true