version: '3.9'
services:
  server:
    container_name: blog_api
    build:
      context: .
      dockerfile: ./Dockerfile
    # image: docker.pkg.github.com/coryball/backend-template/template-server
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
    env_file: prod.env
  postgres:
    container_name: blog_database
    image: postgres:13.3
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      PGDATA: /data/postgres
    env_file: .env
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/
  pg_admin:
    container_name: blog_pgadmin
    image: dpage/pgadmin4:5.4
    restart: unless-stopped
    env_file: .env
    ports:
      - "5050:5050"
  redis:
    container_name: blog_redis
    image: redis:alpine3.13
    restart: unless-stopped
    ports:
      - '6379:6379'
    expose:
      - 6379
    volumes:
      - ./.docker/redis:/data
