version: '3.9'
services:
  server:
    build:
      container_name: blog_api
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    # image: docker.pkg.github.com/coryball/backend-template/template-server
    networks:
      web:
        aliases:
          - api
      blog:
        aliases:
          - api
    env_file:
      - .env
    ports:
      - 4000:4000
  postgres:
    container_name: blog_database
    image: postgres:13.2
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/
    networks:
      blog:
        aliases:
          - database
      web:
        aliases:
          - blog-database
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    container_name: blog_redis
    image: redis:alpine3.13
    restart: unless-stopped
    expose:
      - 6379
    networks:
      blog:
        aliases:
          - redis
      web:
        aliases:
          - blog-redis
    volumes:
      - ./.docker/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
networks:
  web:
    external: true
  blog:
    external: false
